name: auto-release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: '36'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - run: cd 36 && zip -r ../17wanxiaoCheckin.${{ github.ref_name }}.zip ./
      - run: cd 36 && pip install -r requirements.txt -t . && zip -r ../17wanxiaoCheckin-CF.py36.${{ github.ref_name }}.zip ./

      - uses: actions/checkout@v3
        with:
          path: '37'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: cd 37 && pip install -r requirements.txt -t . && zip -r ../17wanxiaoCheckin-CF.py37.${{ github.ref_name }}.zip ./

      - uses: actions/checkout@v3
        with:
          path: '39'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: cd 39 && pip install -r requirements.txt -t . && zip -r ../17wanxiaoCheckin-CF.py39.${{ github.ref_name }}.zip ./

      - run: ls
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: 17wanxiaoCheckin ${{ github.ref_name }}
          body_path: 36/CHANGELOG.md
          draft: false
          prerelease: false
          files: |
            17wanxiaoCheckin.${{ github.ref_name }}.zip
            17wanxiaoCheckin-CF.py36.${{ github.ref_name }}.zip
            17wanxiaoCheckin-CF.py37.${{ github.ref_name }}.zip
            17wanxiaoCheckin-CF.py39.${{ github.ref_name }}.zip